version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    networks:
      - appnetwork
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
networks:
  appnetwork:
    driver: bridge
